project_id = "coblfehkclfjofrshlwl"

[functions.wa-webhook]
verify_jwt = false

[functions.wa-config-test]
verify_jwt = false

[functions.wa-baileys-send]
verify_jwt = false

[functions.rede-create-company-user]
verify_jwt = true

[functions.auto-import-viral]
verify_jwt = false

[functions.scrape-viral-views]
verify_jwt = false
