# fly.toml app configuration file generated for inova-whatsapp on 2026-04-21T23:28:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inova-whatsapp'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[processes]
  app = './dist/index.js'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  processes = ['app']

  [[services.ports]]
    port = 3001
    handlers = ['http']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
