app = "inova-whatsapp"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "./dist/index.js"

[[services]]
  http_checks = []
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 3001

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"